### ISSUE TITLE
Large amount of Visage requests

### ISSUE THREAD

**Issue by unascribed** [Chit132/abyss-overlay#5] opened 2021-06-06 20:12 UTC
Hello, I'm the host of [visage.surgeplay.com](https://visage.surgeplay.com).

Lately I've been receiving a large number of requests from user agents containing AbyssOverlay (such as `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) AbyssOverlay/1.2.2 Chrome/89.0.4389.82 Electron/12.0.1 Safari/537.36`), all for the 2D `/face` endpoint, and this looks like the issue tracker for the project.

It would be a much better user experience (and less load on my servers) if you could render the faces yourself. Visage is primarily intended for browsers, where you cannot just reach out and touch the Mojang API directly due to CORS restrictions. In an Electron app, you don't have to honor CORS. By performing requests on the Node side (outside of the browser), CORS does not apply.

Here is the relevant API method: <a href="https://wiki.vg/Mojang_API#UUID_to_Profile_and_Skin.2FCape">UUID to Profile and Skin/Cape</a>

You can base64-decode the resultant payload as described on the wiki. From this you can download (and cache!) the skin, and use a [Canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) to draw the skin parts. You could also shortcut this by using Visage's `/skin` endpoint, as that is much cheaper for me to provide; it simply copies the data received from Mojang directly without having to involve a renderer, and is aggressively cached. That will still involve a round-trip to my server in eastern Canada, though. Mojang's API is much faster (as you would hope; they're the developers of the best selling game in the world, and I'm just some random nobody.)

Thanks

<em>It would be highly appreciated if you could <a href="https://donate.unascribed.com/?project=3">pitch in to support Visage</a>. It's a service I've run for free for years and is a considerable drain on my hardware resources.</em>

**Comment by unascribed** [comment] 2021-06-07 23:43
Load from Abyss Overlay users has exceeded the point where it is practical for me to continue servicing them. You've broken the golden rule of a free service: *do not overutilize the service to the point it causes other users to have a degraded experience*.

I have firewalled Abyss Overlay requests to all endpoints other than `/skin` to restore functionality. Please do not attempt to ban evade.

**Comment by Cryptizism** [comment] 2021-06-08 12:44
Sorry for the inconvenience, I will talk to the owner (Chit) about this ASAP!

Dearest apologies,
Cryptizism.

**Comment by Chit132** [comment] 2021-06-08 17:50
Oh my, I am so sorry for the inconvenience; I did not know it took such a large toll on your hardware. I'll fix this problem ASAP! I'm just really busy with final exams right now but I will use a different API in the next 3 days. Again, sorry if this has caused a lot of problems for you :( I will close this issue as soon as I have updated to using a new skin API

I have been using Visage for a while and it's always been my #1 choice when I want to retrieve a MC skin for any program I'm working on. I wish I could donate to support you, but I am running my service for completely free as well. So for now, thanks so much for providing your service and letting me know about this. Good luck in the future! <3

**Comment by unascribed** [comment] 2021-06-08 20:06
For the record, since I put the firewall rule in place ~20 hours ago, I've received 1.6M requests from Abyss Overlay users. Extrapolating, this is ~1.92M requests per 24h, meaning Abyss Overlay users were >50% of Visage load. My puny server has been buckling under load regularly for the past couple weeks, initially from a weird Google-Document-Conversion request flood, and then from a surge in popularity of Abyss Overlay.

I'm glad you find Visage useful and encourage you to continue using it for websites and such, but the renders aren't free for me to make, especially on the tiny server I use now that is a small fraction of the power of the server I had when I started Visage. As said, you can use the `/skin` endpoint as a shortcut for now if you want less hoops to jump through; but ideally you would just use the Mojang API directly.

**Comment by Chit132** [comment] 2021-06-08 21:54
I will be switching from Visage to the Mojang API as soon as I can within the next few days. I apologize for the inconvenience again :( I didn't know that the overlay took such a massive toll on your servers. Thanks again for the service Visage has provided for the overlay users up until now :) Keep up the great work!

**Closed** 2021-06-27 01:38 UTC

**Comment by Cryptizism** [comment] 2021-06-28 10:14
The update has been released and we have changed our methods. Thank you for arising this and sorry for anything that was caused by our doing.
